"""Executable claim-chain runtime for FLUXV."""

from .core import (
    ClaimComponent,
    ClaimGraph,
    ClaimRuntimeError,
    ForceContribution,
    ForceLedger,
    GraphRunManifest,
    NodeOutput,
    RunConfig,
    StepContext,
)
from .distributed_doublet import (
    DistributedDoubletError,
    DoubletAssemblyReport,
    DoubletBoundaryReport,
    DoubletContinuityReport,
    DoubletVorticityContinuityReport,
    DoubletVelocityReport,
    MaterialWakeBand,
    MaterialWakeHistory,
    MaterialWakeHistoryReport,
    MaterialKelvinReport,
    QuadraticDoubletAssembly,
    QuadraticDoubletElement,
    QuadraticDoubletPatch,
    QuadraticDoubletSurface,
    SheetAverageVelocityReport,
    newborn_material_wake_band,
)
from .work_conjugate_transfer import (
    GeneralizedLoad,
    LoadTransferError,
    RigidResultantReport,
    VirtualWorkReport,
    rigid_body_jacobian,
    rigid_resultant_report,
    transfer_generalized,
    transfer_linear_nodal,
)
from .unified_panel_pressure import (
    PressureLedgerReport,
    UnifiedPanelPressure,
    UnifiedPressureError,
    structured_uvlm_surface_gradient,
    unified_panel_pressure,
)
from .sheet_velocity_projection import (
    ProjectedAssemblySheetVelocity,
    ProjectedAssemblyNormalGeometryVelocity,
    ProjectedSheetVelocity,
    ProjectedNormalGeometryVelocity,
    SheetVelocityProjectionReport,
    project_assembly_sheet_average_velocity,
    project_assembly_vertex_star_normal_geometry_velocity,
    project_sheet_average_velocity,
    project_sheet_normal_geometry_velocity,
    project_vertex_star_normal_geometry_velocity,
)
from .material_sheet_advection import (
    MaterialAdvectionReport,
    MaterialAdvectionStep,
    NormalGeometryAdvectionStep,
    advance_material_surface_heun,
    advance_surface_normal_geometry_heun,
    self_induced_geometry_velocity,
    self_induced_normal_geometry_velocity,
    self_induced_vertex_star_normal_velocity,
)
from .n1_dde_interface import (
    N1DDEInterfaceError,
    N1DDEOrientation,
    dde_mu_to_n1_gamma,
    interface_orientation,
    n1_gamma_to_dde_mu,
)
from .global_conservation import (
    ConservationBlockReport,
    ConservationEquationBlock,
    GlobalConservationError,
    GlobalConservationSolution,
    GlobalConservationSystem,
)
from .material_helmholtz import (
    MaterialHelmholtzReport,
    material_p2_helmholtz_report,
)
from .dual_side_bernoulli import (
    DualSideBernoulli,
    DualSideBernoulliError,
    PairedWallSourceReport,
    dual_side_moving_bernoulli,
    moving_wall_circulation_source,
    paired_thin_sheet_source_report,
)
from .doublet_potential import (
    DoubletPotentialLimits,
    dde_potential_side_limits,
    element_doublet_potential,
    surface_doublet_potential,
    surface_sheet_average_potential,
)
from .surface_vorticity_inventory import (
    SurfaceInventoryBudgetReport,
    SurfaceInventoryError,
    surface_inventory_budget_report,
)
from .viscous_shell_geometry import (
    DualSurfaceShell,
    ViscousShellGeometryError,
    naca4_dual_surface_shell,
    naca4_half_thickness,
    naca4_mean_line,
    rigidly_transform_shell,
)
from .thick_body_neumann_shadow import (
    ClosedTriangularMesh,
    NeumannSourceSolution,
    RoboEagleClosedShell,
    SourcePanelInfluence,
    ThickBodyNeumannError,
    close_roboeagle_dual_surface_shell,
    closed_triangular_mesh,
    constant_source_polygon_influence,
    solve_conditioned_neumann_source,
    source_influence_matrix,
)
from .surface_ibl_state import (
    SurfaceIBLBudgetReport,
    SurfaceIBLError,
    SurfaceIBLFields,
    SurfaceIBLPhysicalFlux,
    SurfaceIBLSourceTerms,
    rotate_surface_ibl_fields,
    surface_ibl_budget_report,
    surface_ibl_physical_flux,
    surface_ibl_source_terms,
)
from .moving_separation_flux import (
    MovingSeparationFlux,
    moving_separation_ibl_flux,
)
from .deforming_shell_kinematics import (
    DeformingDualSurfaceKinematics,
    DeformingShellError,
    DualSurfaceSnapshot,
    StructuredSurfaceGeometry,
    deforming_dual_surface_kinematics,
    dual_surface_snapshot,
    rigidly_transform_surface_geometry,
    structured_surface_geometry,
)
from .implicit_claim_group import (
    ImplicitBlockResidual,
    ImplicitClaimGroup,
    ImplicitClaimGroupError,
    ImplicitClaimGroupSolution,
    ImplicitIterationReport,
)
from .vortex_entrainment_sheet import (
    ReleaseJunctionReport,
    VortexEntrainmentBalance,
    VortexEntrainmentError,
    VortexEntrainmentInfluence,
    equal_density_mass_flux_jump,
    release_junction_report,
    vortex_entrainment_local_balance,
    vortex_entrainment_velocity,
)
from .near_wall_profile_collapse import (
    IBLVESProfileProjection,
    NearWallProfile,
    NearWallProfileError,
    project_near_wall_profile,
)
from .near_wall_field_contract import (
    NearWallFieldContractError,
    NearWallFieldContractReport,
    NearWallFieldDataset,
    NearWallFieldProvenance,
    RequiredNearWallCoverage,
    aggregate_missing_coverage,
    assert_no_forbidden_targets,
    validate_near_wall_field_dataset,
)
from .material_spike_geometry import (
    MaterialCurvatureChange,
    MaterialSpikeGeometryError,
    MaterialSurfaceCurvature,
    material_curvature_change,
    material_surface_curvature,
    proper_euclidean_observer_transform,
)
from .near_wall_material_flow_map import (
    NearWallFlowMapError,
    NearWallMaterialFlowMap,
    integrate_near_wall_material_flow_map,
)
from .material_backbone_conditions import (
    MaterialBackboneConditionDiagnostics,
    MaterialBackboneConditionError,
    material_backbone_condition_diagnostics,
)
from .n1_thick_shell_adapter import (
    N1ActualShellKinematics,
    N1CollocationReplay,
    N1IncidentVelocityLedger,
    N1SnapshotTriplet,
    N1StepSnapshot,
    N1SymmetryRole,
    N1ThickShellAdapterError,
    build_actual_shell_kinematics_from_mean_surfaces,
    build_n1_actual_shell_kinematics,
    evaluate_n1_incident_velocity,
    parse_n1_snapshot_triplet,
    production_ring_field_velocity,
    replay_n1_collocation_boundary,
)
from .thick_body_trailing_edge import (
    ActiveFilament,
    ClosedSurfaceFluxLedger,
    FilamentChannelTopology,
    N1FilamentShellTopologyAudit,
    TrailingEdgeDirectionResidual,
    TrailingEdgeTopologyResidual,
    audit_n1_filament_shell_topology,
    closed_surface_flux_ledger,
    trailing_edge_direction_residual,
    trailing_edge_topology_residual,
)
from .actual_boundary_potential_shadow import (
    ActualBoundaryPotentialEvaluation,
    ActualBoundaryPotentialSolution,
    actual_boundary_potential_matrices,
    evaluate_actual_boundary_potential,
    solve_actual_boundary_potential,
)
from .actual_boundary_p2_galerkin import (
    ActualBoundaryP2GalerkinSolution,
    ClosedP2Topology,
    PairedP2TriangleIntegral,
    closed_p2_topology,
    element_basis_doublet_potential_line_reduced,
    paired_p2_triangle_integral,
    solve_actual_boundary_p2_galerkin,
)
from .circulation_cut_oracle import (
    CircularP2TraceEvaluation,
    CirculationCutError,
    circular_p2_trace,
)
from .joukowski_kutta_oracle import (
    JoukowskiP2Evaluation,
    joukowski_p2_kutta_trace,
)
from .finite_angle_sheet_formation import (
    FiniteAngleSheetError,
    FiniteAngleSheetFormation,
    finite_angle_sheet_formation,
)
from .blunt_base_topology import (
    BluntBaseTopology,
    BluntBaseTopologyError,
    naca4_blunt_base_topology,
)
from .blunt_base_identifiability import (
    BluntBaseCornerWitness,
    blunt_base_corner_witnesses,
)
from .classified_p2_cut_topology import (
    ClassifiedP2CutError,
    ClassifiedP2CutTopology,
    classified_p2_cut_topology,
)
from .actual_boundary_body_wake import (
    ActualBoundaryBodyWakeSolution,
    MaterialWakeCutAttachment,
    solve_actual_boundary_body_wake_p2,
)
from .material_wake_time_march import (
    ExplicitMidpointWakeMarch,
    ExplicitMidpointWakeStep,
    march_actual_boundary_material_wake_explicit_midpoint,
)
from .constrained_material_wake_advection import (
    ConstrainedWakeAdvectionReport,
    ConstrainedWakeAdvectionStep,
    advance_constrained_material_wake_heun,
)
from .wake_gauge_transport import (
    MaterialGaugeTransportIdentity,
    material_potential_jump_ale_identity,
)
from .p2_surface_material_transport import (
    ContinuousP2ScalarTopology,
    P2ConstrainedTransportRate,
    P2EssentialScalarTrace,
    P2PatchMaterialTransportOperator,
    P2SurfaceMaterialTransportOperator,
    P2TransportBoundaryRoles,
    assemble_p2_patch_material_transport,
    assemble_p2_surface_material_transport,
    continuous_p2_scalar_topology,
    p2_essential_trace_transport_rate,
)
from .actual_body_wake_velocity import (
    ActualBodyWakeVelocityError,
    ActualBodyWakeVelocityLedger,
    ExternalIncidentField,
    VALIDATED_EDGE_QUADRATURE,
    WakeSheetQuery,
    evaluate_actual_body_wake_sheet_velocity,
    material_wake_assembly,
    wake_sheet_interior_query,
)
from .characteristic_birth_slab import (
    CharacteristicBirthSlab,
    CharacteristicBirthSlabError,
    CharacteristicBirthSlabReport,
    solve_p2_characteristic_birth_slab,
)
from .actual_wake_repeated_insertion import (
    ActualWakeRepeatedInsertionStep,
    ActualWakeRepeatedInsertionStepReport,
    ReleasedOldMaterialStage,
    advance_actual_wake_repeated_insertion_midpoint,
)
from .actual_wake_direct_trace import (
    solve_actual_wake_coupled_newborn_trace_direct,
)

__all__ = [
    "ClaimComponent", "ClaimGraph", "ClaimRuntimeError", "ForceContribution",
    "ForceLedger", "GraphRunManifest", "NodeOutput", "RunConfig", "StepContext",
    "DistributedDoubletError", "DoubletAssemblyReport",
    "DoubletBoundaryReport", "DoubletContinuityReport",
    "DoubletVorticityContinuityReport",
    "DoubletVelocityReport", "MaterialKelvinReport", "MaterialWakeBand",
    "MaterialWakeHistory", "MaterialWakeHistoryReport",
    "QuadraticDoubletAssembly", "QuadraticDoubletElement",
    "QuadraticDoubletPatch", "QuadraticDoubletSurface",
    "SheetAverageVelocityReport",
    "newborn_material_wake_band",
    "GeneralizedLoad", "LoadTransferError", "RigidResultantReport",
    "VirtualWorkReport", "rigid_body_jacobian", "rigid_resultant_report",
    "transfer_generalized", "transfer_linear_nodal",
    "PressureLedgerReport", "UnifiedPanelPressure", "UnifiedPressureError",
    "structured_uvlm_surface_gradient", "unified_panel_pressure",
    "ProjectedAssemblySheetVelocity",
    "ProjectedAssemblyNormalGeometryVelocity", "ProjectedSheetVelocity",
    "ProjectedNormalGeometryVelocity",
    "SheetVelocityProjectionReport",
    "project_assembly_sheet_average_velocity",
    "project_assembly_vertex_star_normal_geometry_velocity",
    "project_sheet_average_velocity",
    "project_sheet_normal_geometry_velocity",
    "project_vertex_star_normal_geometry_velocity",
    "MaterialAdvectionReport", "MaterialAdvectionStep",
    "NormalGeometryAdvectionStep", "advance_material_surface_heun",
    "advance_surface_normal_geometry_heun",
    "self_induced_geometry_velocity",
    "self_induced_normal_geometry_velocity",
    "self_induced_vertex_star_normal_velocity",
    "N1DDEInterfaceError", "N1DDEOrientation",
    "dde_mu_to_n1_gamma", "interface_orientation",
    "n1_gamma_to_dde_mu",
    "ConservationBlockReport", "ConservationEquationBlock",
    "GlobalConservationError", "GlobalConservationSolution",
    "GlobalConservationSystem",
    "MaterialHelmholtzReport", "material_p2_helmholtz_report",
    "DualSideBernoulli", "DualSideBernoulliError",
    "PairedWallSourceReport", "dual_side_moving_bernoulli",
    "moving_wall_circulation_source",
    "paired_thin_sheet_source_report",
    "DoubletPotentialLimits", "dde_potential_side_limits",
    "element_doublet_potential", "surface_doublet_potential",
    "surface_sheet_average_potential",
    "SurfaceInventoryBudgetReport", "SurfaceInventoryError",
    "surface_inventory_budget_report",
    "DualSurfaceShell", "ViscousShellGeometryError",
    "naca4_dual_surface_shell", "naca4_half_thickness",
    "naca4_mean_line", "rigidly_transform_shell",
    "ClosedTriangularMesh", "NeumannSourceSolution",
    "RoboEagleClosedShell", "SourcePanelInfluence",
    "ThickBodyNeumannError", "close_roboeagle_dual_surface_shell",
    "closed_triangular_mesh", "constant_source_polygon_influence",
    "solve_conditioned_neumann_source", "source_influence_matrix",
    "SurfaceIBLBudgetReport", "SurfaceIBLError", "SurfaceIBLFields",
    "SurfaceIBLPhysicalFlux", "SurfaceIBLSourceTerms",
    "rotate_surface_ibl_fields", "surface_ibl_budget_report",
    "surface_ibl_physical_flux", "surface_ibl_source_terms",
    "MovingSeparationFlux", "moving_separation_ibl_flux",
    "DeformingDualSurfaceKinematics", "DeformingShellError",
    "DualSurfaceSnapshot", "StructuredSurfaceGeometry",
    "deforming_dual_surface_kinematics", "dual_surface_snapshot",
    "rigidly_transform_surface_geometry",
    "structured_surface_geometry",
    "ImplicitBlockResidual", "ImplicitClaimGroup",
    "ImplicitClaimGroupError", "ImplicitClaimGroupSolution",
    "ImplicitIterationReport",
    "ReleaseJunctionReport", "VortexEntrainmentBalance",
    "VortexEntrainmentError", "VortexEntrainmentInfluence",
    "equal_density_mass_flux_jump", "release_junction_report",
    "vortex_entrainment_local_balance",
    "vortex_entrainment_velocity",
    "IBLVESProfileProjection", "NearWallProfile", "NearWallProfileError",
    "MaterialCurvatureChange", "MaterialSpikeGeometryError",
    "MaterialSurfaceCurvature", "material_curvature_change",
    "material_surface_curvature", "proper_euclidean_observer_transform",
    "NearWallFlowMapError", "NearWallMaterialFlowMap",
    "integrate_near_wall_material_flow_map",
    "MaterialBackboneConditionDiagnostics",
    "MaterialBackboneConditionError",
    "material_backbone_condition_diagnostics",
    "project_near_wall_profile",
    "NearWallFieldContractError", "NearWallFieldContractReport",
    "NearWallFieldDataset", "NearWallFieldProvenance",
    "RequiredNearWallCoverage", "aggregate_missing_coverage",
    "assert_no_forbidden_targets", "validate_near_wall_field_dataset",
    "N1ActualShellKinematics", "N1CollocationReplay",
    "N1IncidentVelocityLedger", "N1SnapshotTriplet",
    "N1StepSnapshot", "N1SymmetryRole",
    "N1ThickShellAdapterError",
    "build_actual_shell_kinematics_from_mean_surfaces",
    "build_n1_actual_shell_kinematics",
    "evaluate_n1_incident_velocity", "parse_n1_snapshot_triplet",
    "production_ring_field_velocity",
    "replay_n1_collocation_boundary",
    "ActiveFilament", "ClosedSurfaceFluxLedger",
    "FilamentChannelTopology", "N1FilamentShellTopologyAudit",
    "TrailingEdgeDirectionResidual", "TrailingEdgeTopologyResidual",
    "audit_n1_filament_shell_topology",
    "closed_surface_flux_ledger",
    "trailing_edge_direction_residual",
    "trailing_edge_topology_residual",
    "ActualBoundaryPotentialEvaluation",
    "ActualBoundaryPotentialSolution",
    "actual_boundary_potential_matrices",
    "evaluate_actual_boundary_potential",
    "solve_actual_boundary_potential",
    "ActualBoundaryP2GalerkinSolution", "ClosedP2Topology",
    "PairedP2TriangleIntegral",
    "closed_p2_topology",
    "element_basis_doublet_potential_line_reduced",
    "paired_p2_triangle_integral",
    "solve_actual_boundary_p2_galerkin",
    "CircularP2TraceEvaluation", "CirculationCutError",
    "circular_p2_trace",
    "JoukowskiP2Evaluation", "joukowski_p2_kutta_trace",
    "FiniteAngleSheetError", "FiniteAngleSheetFormation",
    "finite_angle_sheet_formation",
    "BluntBaseTopology", "BluntBaseTopologyError",
    "naca4_blunt_base_topology",
    "BluntBaseCornerWitness", "blunt_base_corner_witnesses",
    "ClassifiedP2CutError", "ClassifiedP2CutTopology",
    "classified_p2_cut_topology",
    "ActualBoundaryBodyWakeSolution",
    "MaterialWakeCutAttachment",
    "solve_actual_boundary_body_wake_p2",
    "ConstrainedWakeAdvectionReport",
    "ConstrainedWakeAdvectionStep",
    "advance_constrained_material_wake_heun",
    "MaterialGaugeTransportIdentity",
    "material_potential_jump_ale_identity",
    "ContinuousP2ScalarTopology",
    "P2ConstrainedTransportRate",
    "P2EssentialScalarTrace",
    "P2PatchMaterialTransportOperator",
    "P2SurfaceMaterialTransportOperator",
    "P2TransportBoundaryRoles",
    "assemble_p2_patch_material_transport",
    "assemble_p2_surface_material_transport",
    "continuous_p2_scalar_topology",
    "p2_essential_trace_transport_rate",
    "ActualBodyWakeVelocityError",
    "ActualBodyWakeVelocityLedger",
    "ExternalIncidentField",
    "VALIDATED_EDGE_QUADRATURE",
    "WakeSheetQuery",
    "evaluate_actual_body_wake_sheet_velocity",
    "material_wake_assembly",
    "wake_sheet_interior_query",
    "CharacteristicBirthSlab", "CharacteristicBirthSlabError",
    "CharacteristicBirthSlabReport",
    "solve_p2_characteristic_birth_slab",
    "ActualWakeRepeatedInsertionStep",
    "ActualWakeRepeatedInsertionStepReport",
    "ReleasedOldMaterialStage",
    "advance_actual_wake_repeated_insertion_midpoint",
    "solve_actual_wake_coupled_newborn_trace_direct",
]
from .material_birth_flux import (
    MaterialBirthFlux,
    consistent_p2_line_mass,
    finite_angle_material_birth_flux,
)
